-- Autogenerated need item list for drugs
local items = {
    { item = 'opium',                                 thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 6000 },
    { item = 'peyote',                                thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 6000 },
    { item = 'hemp',                                  thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 6000 },
    { item = 'heroin',                                thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 7000 },
}

AddNeedItems(items)
