-- Autogenerated need item list for medical
local items = {
    { item = 'syringe',                               thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 3000 },
    { item = 'bandagesteril',                         thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 3000 },
    { item = 'herbalremedy',                          thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 3000 },
    { item = 'antibiotics',                           thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'use',   duration = 3000 },
}

AddNeedItems(items)
