-- Autogenerated need item list for smokes
local items = {
    { item = 'cigarette',                             thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = 'P_CIGARETTE_CS01X', animation = 'cigarette', duration = 8000 },
    { item = 'cigar',                                 thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = 'P_CIGAR02X',        animation = 'cigar', duration = 9000 },
    { item = 'pipe_smoker',                           thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = 'P_PIPE01X',         animation = 'pipe', duration = 9000 },
    { item = 'pipe',                                  thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = 'P_PIPE01X',         animation = 'pipe', duration = 9000 },
    { item = 'chewingtobacco',                        thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = nil,                 animation = 'chew', duration = 7000 },
    { item = 'peacepipe',                             thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = 'P_PIPE01X',         animation = 'pipe', duration = 9000 },
    { item = 'cigaret',                               thirst = 0,  hunger = 0,  stress = 0, health = 0, stamina = 2, OuterCoreHealthGold = 0, InnerCoreHealthGold = 0, OuterCoreStaminaGold = 0, InnerCoreStaminaGold = 0, remove = true, prop = 'P_CIGARETTE_CS01X', animation = 'cigaret', duration = 8000 },
}

AddNeedItems(items)
